name: Aggregate downstreams

on:
  push:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - uses: ./.github/actions/aggregate-downstreams
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
